package org.pis.project.grpc;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneOffset;

import org.pis.project.proto.CreateProjectRequest;
import org.pis.project.proto.Project;
import org.pis.project.proto.ProjectServiceGrpc;
import org.pis.project.services.ProjectService;
import org.pis.project.services.TeamJoinRequestService;
import org.pis.project.services.TeamMemberService;
import org.pis.project.services.TeamService;
import org.springframework.stereotype.Service;

import com.google.protobuf.Timestamp;

import io.grpc.stub.StreamObserver;
import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class ProjectGrpcService extends ProjectServiceGrpc.ProjectServiceImplBase {

  private final ProjectService projectService;
  private final TeamService teamService;
  private final TeamMemberService teamMemberService;
  private final TeamJoinRequestService teamJoinRequestService;


  @Override
  public void createProject(CreateProjectRequest request, StreamObserver<Project> responseObserver) {
    try {
      // 1. Call your domain service to save to the database
      // I'm assuming your service returns an Entity with an ID and CreatedAt date
      org.pis.project.models.entities.Project newProjectEntity = org.pis.project.models.entities.Project.builder()
          .title(request.getTitle())
          .description(request.getDescription())
          .teacherId(request.getTeacherId())
          .maxStudentsPerTeam(request.getMaxStudentsPerTeam())
          .startDate(Instant.ofEpochSecond(request.getStartDate().getSeconds(), request.getStartDate().getNanos())
              .atZone(java.time.ZoneId.systemDefault()).toLocalDateTime())
          .endDate(Instant.ofEpochSecond(request.getEndDate().getSeconds(), request.getEndDate().getNanos())
              .atZone(java.time.ZoneId.systemDefault()).toLocalDateTime())
          .subjectId(request.getSubjectId())
          .build();

      var savedEntity = projectService.createProject(newProjectEntity);

      // 2. Map your Entity to the Proto Message
      // We use the Builder pattern generated by Protobuf
      Project response = Project.newBuilder()
          .setId(String.valueOf(savedEntity.getId()))
          .setTitle(savedEntity.getTitle())
          .setDescription(savedEntity.getDescription())
          .setTeacherId(savedEntity.getTeacherId())
          .setMaxStudentsPerTeam(savedEntity.getMaxStudentsPerTeam())
          .setStartDate(mapToTimestamp(savedEntity.getStartDate()))
          .setEndDate(mapToTimestamp(savedEntity.getEndDate()))
          .setSubjectId(savedEntity.getSubjectId())
          .build();

      // 3. Send the response and close the stream
      responseObserver.onNext(response);
      responseObserver.onCompleted();

    } catch (Exception e) {
      // 4. Handle errors (e.g., validation or database errors)
      // You can return specific gRPC status codes here
      responseObserver.onError(io.grpc.Status.INTERNAL
          .withDescription("Could not create project: " + e.getMessage())
          .asRuntimeException());
    }
  }

  /**
   * Converts LocalDateTime to google.protobuf.Timestamp using UTC offset.
   */
  private Timestamp mapToTimestamp(LocalDateTime localDateTime) {
    if (localDateTime == null) {
      return Timestamp.getDefaultInstance();
    }

    // 1. Convert LocalDateTime to an Instant (assuming UTC)
    var instant = localDateTime.toInstant(ZoneOffset.UTC);

    // 2. Build the Protobuf Timestamp
    return Timestamp.newBuilder()
        .setSeconds(instant.getEpochSecond())
        .setNanos(instant.getNano())
        .build();
  }
}