global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector-app-metrics"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "otel-collector-internal"
    static_configs:
      - targets: ["otel-collector:8888"]

  - job_name: "blackbox-subject-service-health"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://subject-service:50080/health/live
        labels:
          service: subject-service
          check: liveness
      - targets:
          - http://subject-service:50080/health/ready
        labels:
          service: subject-service
          check: readiness-db
    relabel_configs: &blackbox_relabel
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: "blackbox-evaluation-service-health"
    metrics_path: /probe
    params:
      module: [grpc_health]
    static_configs:
      - targets:
          - evaluation-service:50055
        labels:
            service: evaluation-service
            check: grpc-health
    relabel_configs: *blackbox_relabel

  - job_name: "blackbox-router-health"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://router:8081/health
        labels:
          service: router
          check: liveness
    relabel_configs: *blackbox_relabel

  - job_name: "blackbox-auth-service-health"
    metrics_path: /probe
    params:
      module: [grpc_health]
    static_configs:
      - targets:
          - auth-service:50051
        labels:
            service: auth-service
            check: grpc-health
    relabel_configs: *blackbox_relabel

  - job_name: "blackbox-notification-service-health"
    metrics_path: /probe
    params:
      module: [grpc_health]
    static_configs:
      - targets:
          - notification-service:50052
        labels:
            service: notification-service
            check: grpc-health
    relabel_configs: *blackbox_relabel

  - job_name: "blackbox-frontend-health"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://frontend
        labels:
          service: frontend
          check: http
    relabel_configs: *blackbox_relabel

  - job_name: "blackbox-project-service-health"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://project-service:40054/actuator/health
        labels:
          service: project-service
          check: liveness
    relabel_configs: *blackbox_relabel

