syntax = "proto3";

package eval;

import "common.proto";
import "google/protobuf/timestamp.proto";

service EvaluationService {
  rpc GetSubjectEvaluation(GetSubjectEvaluationRequest) returns (SubjectEvaluation);
  rpc GetProjectEvaluation(GetProjectEvaluationRequest) returns (ProjectEvaluation);

  rpc ListSubjectEvaluations(ListSubjectEvaluationsRequest) returns (ListSubjectEvaluationsResponse);
  rpc ListProjectEvaluations(ListProjectEvaluationsRequest) returns (ListProjectEvaluationsResponse);

  rpc CreateSubjectEvaluation(CreateSubjectEvaluationRequest) returns (SubjectEvaluation);
  rpc CreateProjectEvaluation(CreateProjectEvaluationRequest) returns (ProjectEvaluation);

  rpc UpdateSubjectEvaluation(UpdateSubjectEvaluationRequest) returns (SubjectEvaluation);
  rpc UpdateProjectEvaluation(UpdateProjectEvaluationRequest) returns (ProjectEvaluation);

  rpc DeleteSubjectEvaluation(DeleteEvaluationRequest) returns (common.Ack);
  rpc DeleteProjectEvaluation(DeleteEvaluationRequest) returns (common.Ack);
}

message SubjectEvaluation {
  string id = 1;
  string subject_id = 2;
  string student_id = 3;
  string grade = 4;
  google.protobuf.Timestamp timestamp = 7;
}

message ProjectEvaluation {
  string id = 1;
  string project_id = 2;
  string team_id = 3;
  string evaluator_teacher_id = 4;
  float total_score = 5;
  string feedback = 6;
  google.protobuf.Timestamp timestamp = 7;
}

message GetSubjectEvaluationRequest {
  string evaluation_id = 1;
}

message GetProjectEvaluationRequest {
  string project_id = 1;
  string team_id = 2;
  string evaluator_teacher_id = 4;
}

message CreateSubjectEvaluationRequest {
  string subject_id = 1;
  string student_id = 2;
  string grade = 3;
}

message CreateProjectEvaluationRequest {
  string subject_id = 1;
  string project_id = 2;
  string team_id = 3;
  float total_score = 4;
  string feedback = 5;
}

message ListSubjectEvaluationsRequest {
  string subject_id = 1;
}

message ListSubjectEvaluationsResponse {
  repeated SubjectEvaluation evaluations = 1;
}

message ListProjectEvaluationsRequest {
  string project_id = 1;
  string student_id = 2;
  string evaluator_teacher_id = 3;
}

message ListProjectEvaluationsResponse {
  repeated ProjectEvaluation evaluations = 2;
}

message UpdateSubjectEvaluationRequest {
  string subject_id = 2;
  string student_id = 3;
  string grade = 4;
}

message UpdateProjectEvaluationRequest {
  string project_id = 2;
  string team_id = 3;
  float total_score = 5;
  string feedback = 6;
}

message DeleteEvaluationRequest {
  string evaluation_id = 1;
}

