syntax = "proto3";

package eval;

import "common.proto";
import "google/protobuf/timestamp.proto";

service EvaluationService {
  rpc GetProjectEvaluation(GetProjectEvaluationRequest) returns (ProjectEvaluation);
  rpc ListProjectEvaluations(ListProjectEvaluationsRequest) returns (ListProjectEvaluationsResponse);
  rpc CreateProjectEvaluation(CreateProjectEvaluationRequest) returns (ProjectEvaluation);
  rpc UpdateProjectEvaluation(UpdateProjectEvaluationRequest) returns (ProjectEvaluation);
  rpc DeleteProjectEvaluation(DeleteEvaluationRequest) returns (common.Ack);
}

message ProjectEvaluation {
  string id = 1;
  string project_id = 2;
  string team_id = 3;
  string evaluator_teacher_id = 4;
  float total_score = 5;
  string feedback = 6;
  google.protobuf.Timestamp timestamp = 7;
}

message GetProjectEvaluationRequest {
  string project_id = 1;
  string team_id = 2;
  optional string evaluator_teacher_id = 4;
}

message CreateProjectEvaluationRequest {
  string subject_id = 1;
  string project_id = 2;
  string team_id = 3;
  float total_score = 4;
  string feedback = 5;
}

message ListProjectEvaluationsRequest {
  optional string project_id = 1;
  optional string student_id = 2;
  optional string evaluator_teacher_id = 3;
}

message ListProjectEvaluationsResponse {
  repeated ProjectEvaluation evaluations = 1;
}

message UpdateProjectEvaluationRequest {
  string evaluation_id = 1;
  optional float total_score = 2;
  optional string feedback = 3;
}

message DeleteEvaluationRequest {
  string evaluation_id = 1;
}

