spring.datasource.url=jdbc:postgresql://project-postgres:${POSTGRES_PORT}/${POSTGRES_DB}

spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.grpc.server.port=${GRPC_PORT}
server.port=${HTTP_PORT}

spring.grpc.client.channels.auth.address=${AUTH_GRPC_ENDPOINT:auth-service:50051}
spring.grpc.client.channels.notification.address=${NOTIFICATION_GRPC_ENDPOINT:auth-service:50052}
spring.grpc.client.channels.subject.address=${SUBJECT_GRPC_ENDPOINT:subject-service:50053}
spring.grpc.client.channels.evaluation.address=${EVALUATION_GRPC_ENDPOINT:evaluation-service:50055}

spring.jpa.open-in-view=false
